version: '3.7'
networks:
    bestrip:
        name: bestrip
        driver: bridge

services:
    postgres:
        container_name: postgres
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: bestripdb
        ports:
            - '15432:5432'   
        networks:
            - bestrip     
      
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin
            PGADMIN_DEFAULT_PASSWORD: 123
        ports: 
            - '16432:80'
        depends_on: 
            - postgres
        networks:
            - bestrip

